[project]
name = "event-calplot"
version = "0.1.0"
description = "A Python package for visualizing event data as calendar heatmaps."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas==2.3.3",
    "plotly==6.3.1",
]
