name: Publish to PyPI

on:
  push:
    branches:
        - main
    tags:
        - 'v*.*.*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        environment: "pypi"
        permissions:
            id-token: write
            contents: read
        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v5

            # Set up Python
            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"

            # Set up Python using uv    
            - name: Install uv
              uses: astral-sh/setup-uv@v6
              with:
                enable-cache: true

            # Install dependencies
            - name: Install the project
              run: uv sync --locked --all-extras --dev
            
            # Build the package
            - name: Build package
              run: uv build
            
            # Publish to PyPI
            - name: Publish to PyPI
              run: uv publish
